### ISSUE TITLE
Column formatter only receives data for its own column

### ISSUE THREAD

**Issue by kilsen** [maheshsenni/react-treelist#12]
The column formatter only receives a single argument -- the data for that column. It would be helpful if a second argument could be passed in, containing the entire row. That way, the logic in the custom formatter could examine other attributes of the data when formatting the column value for display. For example, it could conditionally put a hyperlink or a button in the cell based on other properties.

**Comment by maheshsenni** [comment]
@kilsen this could be a useful feature. Added this in version `1.1.0`.

**Comment by kilsen** [comment]
Thank you very much for adding this feature! I'm now able to put an icon in a column that a user can click to view detail about the row  -- and for rows that the user lacks sufficient permission to see the detail, I can omit the icon.
