### ISSUE TITLE
hash calculation is a bit slow on a big tree

### ISSUE THREAD

**Issue by mbarto** [maheshsenni/react-treelist#15]
Using memoize functions would speed up the tree functions (e.g. expand / collapse of nodes) when the tree nodes do not change.

**Comment by maheshsenni** [comment]
Do you mean [here](https://github.com/maheshsenni/react-treelist/blob/master/src/lib/TreeList.js#L124)?

I like the idea, but if I have to memoize the results of this function, what could be an appropriate key for the cache? It would have been straight-forward if the hash function was using just scalar values.

**Comment by mbarto** [comment]
Have a look here: https://github.com/geosolutions-it/react-treelist/blob/css_on_rows/src/lib/TreeList.js#L128

I used lodash memoize. I was also thinking to use https://www.npmjs.com/package/memoize-one

With memoize-one we only store one item in cache, so we don't risk memory leaks, and it should be enough to cache the current tree (obviously the hash would be recalculated if the tree changes, but the issue here was that it was recalculated also if the tree didn't change, and this was slow in my use case).

**Comment by maheshsenni** [comment]
Makes sense, especially if we store only one item in cache.

How will the memoize implementation know that the tree data has changed? Consider the below code for example:

```js
var obj1 = { 'a': 1, 'b': 2 };
 
var constFunc = function() { return Math.random(); };
var memoizedConst = _.memoize(constFunc);

console.log('Obj1 is:', obj1)
console.log('Obj1 hash is: ', memoizedConst(obj1));
// returns cached value
console.log('Obj1 hash again: ', memoizedConst(obj1));
obj1.a = 2;
console.log('Changing property value of obj1', obj1)
// returns cached value but the data has changed
// ideally a new value should be returned
console.log('Obj1 hash after value change: ', memoizedConst(obj1));
```

Did I understand your solution correctly?

**Comment by mbarto** [comment]
My version works with the assumption the data is immutable, so if the data changes also the obj ref changes, while if the data does not change, also the obj ref doesn't. This means you can compare with a simple oldData === data.

Eventually memoizeOne allows using a different "comparator".

We could do this way:
 * disable memoization by default
 * enable memoization with trivial compare with a flag (e.g. immutableData: true); thinking out loud, maybe with immutable data we don't need hash computation at all, we can simply rely on === operator to know when the tree is changed (this is the purpose of the current hash calculation, right?)
 * eventually allow memoization using a custom comparator (don't know if this is worth the effort, it would be probably slower than calculating the hash anyway)

**Comment by maheshsenni** [comment]
Ideally you would expect the data to be immutable and all changes to it will change its reference. But we don't have control over how the parent application is managing its state. Since this affects the component's data integrity, the component should default to minimizing this risk. I am inclined towards having a flag that enables memoization and not enabled by default. What do you think?

**Comment by mbarto** [comment]
Agree, I can produce a PR with this behaviour

**Comment by maheshsenni** [comment]
Awesome, thanks!

**Comment by mbarto** [comment]
Working on it I had another idea: what do you think of "externalizing" the hash calculation, so that we can customize it. So, instead of adding code to memoize in the library, I would define a property (dataHash) that, if defined, would replace the internal hash calculation. The only issue I see is that current hash is working on data and sort info: we could split hash calculation in two (data and internal state) and concatenate the two pieces to get the final hash. What do you think?

**Comment by maheshsenni** [comment]
Nice idea! If we are externalizing hash calculation, at that point the component might as well accept a simple property (say, `refresh`) that will change every time the data changes. It can be a hash  of the data or any value (for example, `new Date().getTime()`) for that matter. The component will (force) re-render when this property changes.
