### ISSUE TITLE
Ability to dynamically style rows based on node attributes

### ISSUE THREAD

**Issue by mbarto** [maheshsenni/react-treelist#16]
Using a new option (e.g. rowClass) that could be a string or a function it would be possible to assign css to rows based on the row node properties

**Comment by maheshsenni** [comment]
There is an [existing column level option](https://maheshsenni.github.io/react-treelist/demo/custom-styles.html) which kind of overlaps this functionality. I think there is scope for both of these options. 

1. Accept a new `rowClass` option which can be a string or a function. Providing a string value will apply the class to all rows. If a function is passed, it will be called with row values as an argument for very row (performance?!) and the function's return value is expected to be a class name for the row.
2. Modify the existing column `class` option to accept a string/function (right now only strings are accepted) and it will be act similar to the `rowClass` option.

Would you be interested to submitting a PR?

**Comment by maheshsenni** [comment]
Awesome! Thanks @mbarto, looking forward to the PR.
