### ISSUE TITLE
how can i add some features to my list items ?

### ISSUE THREAD

**Issue by shadoo77** [maheshsenni/react-treelist#24]
I think that i need sometimes to add some styles to my list items like color or even icon, but how can i do that here , cuz i see too little options

**Comment by maheshsenni** [comment]
Try the `class` [option](https://maheshsenni.github.io/react-treelist/demo/custom-styles.html) which accepts a string/function to add custom styles to items.

**Comment by maheshsenni** [comment]
@shadoo77 Is the `class` working for you?

**Comment by shadoo77** [comment]
I didn’t use the package cuz i can’t put onClick event on the links also,
so i made my own treeview
Anyway thanx

Op za 1 jun. 2019 om 02:29 schreef Mahesh Senniappan <
notifications@github.com>

**Comment by maheshsenni** [comment]
Thanks for responding. I'll close this issue.
