### ISSUE TITLE
Max data that the tree component can support?

### ISSUE THREAD

**Issue by arjunaria** [maheshsenni/react-treelist#25]
Mahesh, I am getting and error  RangeError: Maximum call stack size exceeded when i use a data json with around 2500 rows.
Can you advise on the max limit of data that can be used

react.development.js:623 Uncaught RangeError: Maximum call stack size exceeded
    at Object.hasOwnProperty (<anonymous>)
    at hasValidRef (react.development.js:623)
    at Object.createElement (react.development.js:765)
    at Object.createElementWithValidation [as createElement] (react.development.js:1733)
    at createRow (Row.js:135)
    at Body.makeRowsRecursive (Body.js:109)
    at eval (Body.js:115)
    at Array.forEach (<anonymous>)
    at Body.makeRowsRecursive (Body.js:114)
    at eval (Body.js:115)

**Comment by maheshsenni** [comment]
@arjunaria I don't think the stack size problem is related to the component. Here is a fiddle with the treelist rendering a dataset of 11000 rows. I have seen this happen before if the data has cyclic relationships.

https://jsfiddle.net/201p9nuj/show

**Comment by arjunaria** [comment]
yes the data does have some cyclic relationships - is there any fix other than the using hierarchical data unique Id..

**Comment by maheshsenni** [comment]
I am afraid that there is no fix as such. I would consider this as a data problem rather than an issue for the component itself.

**Comment by arjunaria** [comment]
I would want to show a loader to inform the user  till the table is rendered completely as i am not using a fixed table height.  where do I get to know the table has rendered and  ready..

**Comment by maheshsenni** [comment]
You could try `componentDidMount` on the parent component wrapping the treelist. Closing this issue as this is not an issue for the component.
