### ISSUE TITLE
selection of multiple rows

### ISSUE THREAD

**Issue by arjunaria** [maheshsenni/react-treelist#26]
How do i have multiple rows selected in selected state the tree as currently the option is only to have 1 row selected where the rowid is stored in the state.

**Comment by maheshsenni** [comment]
The current options only allow one row to be selected, but I am okay with adding support for selecting multiple rows. I'll see if I can get to it but I would welcome a PR for this.

**Comment by arjunaria** [comment]
I was able to achieve by storing an array of Id in the selectedState..

**Comment by maheshsenni** [comment]
Awesome! Glad you got it working. Can this issue be closed?
