### ISSUE TITLE
Add an option to place the expand/collapse indicator on a different column

### ISSUE THREAD

**Issue by jktravis** [maheshsenni/react-treelist#3]
Would like to be able to select which column has the expand/collapse icon. Maybe in the columns options, mark the column with something like: 

```js
{ title: 'column name', field: 'fieldName', type: 'string', expand: true }
```

**Comment by maheshsenni** [comment]
I can certainly take a look at this. But I am thinking that having the icon in the first column looks more elegant. Do you have an example you could link me to? I just want to see how the UI will look like.

**Comment by jktravis** [comment]
Here's an example. 

[http://runner.telerik.io/fullscreen/oHAmO](http://runner.telerik.io/fullscreen/oHAmO)

Sometimes, one may need the first column to be something that doesn't make sense to expand upon. In the above, it makes more sense that the last name be the "root" of the expansion.

**Comment by maheshsenni** [comment]
Thanks. Will take a look at it this week.

**Comment by maheshsenni** [comment]
Added the option to do this. Any column can now show expand/collapse icons with the `expand` option set to `true`.
