### ISSUE TITLE
Question: How performant is this list?

### ISSUE THREAD

**Issue by jktravis** [maheshsenni/react-treelist#5]
Just curious as to how much data this tree can handle before it begins to have a noticeable performance hit.

**Comment by maheshsenni** [comment]
At the moment it can handle only small data sets (~200 with all rows expanded), but I am working on virtual scrolling which should allow large data sets to be displayed. I am planning to complete it by the end of this week. Will keep this issue open until then.

**Comment by maheshsenni** [comment]
From v0.2.1, treelist can now display large data sets. Virtual scrolling takes over when `height` options is specified.
