### ISSUE TITLE
Cyclic dependency check

### ISSUE THREAD

**Issue by Vineeth-Mohan** [maheshsenni/react-treelist#9]
Thanks for the wonderful component. 

We did notice one slight issue though.
As the data is flattened and not in a heirachiel manner , there is scope for cyclic dependency and the whole code can go into a infinite recursive mode.
```
  {
    "location": "ML",
    "id": "ML",
    "parentId": "ML"
  },
```
If we have a element like above in the data , the whole thing will go into infinite recursion and kill the browser. 

So my suggestion would be to take heirachiel JSON as input or check for cyclic dependency on the flattened data before executing it.

**Comment by maheshsenni** [comment]
Glad you like the component and thanks for pointing this out.

I am much more inclined to check for cyclic dependency now than use hierarchical data (may be for the future). Metadata is generated for easy lookup while rendering child rows. I presume this would be the appropriate place to check for cyclic dependency.

https://github.com/maheshsenni/react-treelist/blob/master/src/js/util/TreeUtils.js#L7

**Comment by maheshsenni** [comment]
On second thought, I don't think checking for cyclic dependencies can be a responsibility for this component and there is no way for the component to recover and render even if it detects there is cyclic dependency. Closing this issue as it has been a while since this issue was created.
